name: Terraform Deploy to Azure (UAT Environment)

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform-uat:
    runs-on: ubuntu-latest

    environment: Uat  # Specifies the UAT environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the version of Terraform you are using

      # Azure login using secrets for the UAT environment
      - name: Login to Azure
        uses: Azure/login@v2
        with:
          client-id: 66d17a9d-7681-4c58-86e6-d4f4fa45995d 
          tenant-id: e4e34038-ea1f-4882-b6e8-ccd776459ca0
          client-secret: Qpa8Q~6wQcEjNZrKOcm2enoSQWUTZ.t~dLjWAb9A
          subscription-id: 23a10725-0f45-4b82-88e0-189c6e8c94a9

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Format (optional but recommended for code consistency)
      - name: Terraform Format
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan (creates an execution plan)
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply Terraform plan (deploy infrastructure to UAT)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Apply only on main branch
        run: terraform apply -auto-approve tfplan
